version: "3.8"

services:
  api:
    build:
      context: ./frontend
    container_name: frontend-api
    environment:
      DATABASE_HOST: db 
      DATABASE_USER: appuser
      DATABASE_PASS: apppass
      DATABASE_PORT: 3306
      DATABASE_DB: appdb
    ports:
      - "5000:5000"
    links:
      - db      
    restart: always

  db:
    build:
      context: ./backend
    container_name: backend-db
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: dbrootpass
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: